example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import create_wishlist
from wishlist.views import show_ajax
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id 
from wishlist.views import show_xml_by_id 
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_ajax, name='show_ajax'),
    path('ajax/submit/', create_wishlist, name= 'create_wishlist'),


]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from http import cookies
from http.cookiejar import Cookie
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/wishlist/login/')
    
def show_wishlist(request):
    #return render(request, "wishlist.html")
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Dina 🌸',
        'last_login': request.COOKIES['last_login'],    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    #ika JSON
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    #Jika XM
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) 
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_ajax(request):
    return render(
        request,
        'wishlist_ajax.html',
        {
            'nama': 'Dina 🌸',
            'last_login': request.COOKIES['last_login']
        }
    )

@login_required(login_url='/wishlist/login/')
def create_wishlist(request):
    if request.method == "POST":
        nama_barang = request.POST.get("nama_barang")
        harga_barang = request.POST.get("harga_barang")
        deskripsi = request.POST.get("deskripsi")

        create_barang = BarangWishlist.objects.create(
            nama_barang=nama_barang, 
            harga_barang=harga_barang, 
            deskripsi=deskripsi
        )
        return JsonResponse(
            {
                'error':False,
                'msg':'Success'
            }
        )
    return redirect('wishlist:show_ajax')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous" ></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<h5>Nama: </h5>
<p>Dina 🌈 🥳 🌸 🏃‍♀️ 🦋</p>

<table>
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
    {% endfor %}
</table>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar" style="background-color: #e5ccf2;">
    <div class="container-fluid">
      <a class="navbar-brand">DinaBar🍻</a>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button style="margin-right: 10px" class="btn btn-outline-success" type="submit">Search</button>
        <button style="margin-right: 10px" class="btn btn-outline-success me-2" type="button"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
      </form>
    </div>
  </nav>

<h5 style="padding: 10px;">Nama: </h5>
<p style="padding: 10px;">Dina 🌈 🥳 🌸 🏃‍♀️ 🦋</p>

<table>
    <tr>
    <th style="padding: 10px;">Nama Barang</th>
    <th style="padding: 10px;">Harga Barang</th>
    <th style="padding: 10px;">Deskripsi</th>
    </tr>
    
</table>
<h2>Formulir barang baru</h2>
  <form method="POST" action="">
    {% csrf_token %}
    <table>
      <tr>
        <td>Nama Barang: </td>
        <td><input type="text" id="nama_barang" name="nama_barang" placeholder="Nama Barang" class="form-control"></td>
      </tr>

      <tr>
        <td>Harga Barang: </td>
        <td><input type="number" id="harga_barang" name="harga_barang" placeholder="Harga Barang" class="form-control"></td>
      </tr>

      <tr>
        <td>Deskripsi: </td>
        <td><textarea class="form-control" id="deskripsi" name="deskripsi"></textarea></td>
      </tr>

      <tr>
        <td></td>
        <td><input class="btn btn-primary" type="submit" value="Submit" id="newBtn"></td>
      </tr>
    </table>
  </form>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  function postNew(e) {
    e.preventDefault()
    const namaBarang = $("#nama_barang").val()
    const hargaBarang = $("#harga_barang").val()
    const deskripsi = $("#deskripsi").val()

    const data = {
      nama_barang: namaBarang,
      harga_barang: hargaBarang,
      deskripsi,
      csrfmiddlewaretoken: "{{ csrf_token }}"
    }

    $.ajax({
      type: 'POST',
      url: '{% url "wishlist:create_wishlist" %}',
      data: data, 
      success: () => {
        alert("Done!")
        fetchData()
      },
      dataType: 'json'
    });
  }

  function writeTable(data) {
    const table = $("#tabel")
    table.empty()
    for (let i = 0; i < data.length; i++) {
      table.append(`
        <tr>
          <td>${data[i].fields.nama_barang}</td>
          <td>${data[i].fields.harga_barang}</td>
          <td>${data[i].fields.deskripsi}</td>
        </tr>
        `)
    }
  }

  function fetchData() {
    $.get("/wishlist/json", writeTable)
  }

  $(document).ready(() => {
    $("#newBtn").click(postNew)
    fetchData()
  })
</script>

<p style="padding: 10px;">Sesi terakhir login: {{ last_login }}</p>

{% endblock content %}